spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gardening?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gardening
    password: gardening

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

api:
  key: 20240206CEALQSMDGKEMGAKWYTOULQ

cloud:
  aws:
    s3:
      bucket: qorehbucket
    credentials:
      access-key: AKIAV5F35FRO2RFGUJHF
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


